Improved the `Hypocycloid` class docstring
chris-greening/spyrograph pull request #85
Opened 2023-03-30 21:15 UTC by jbxamora

## Description
Simple improvement of docstring to more technical and concise
Do not include any personal data.

Fixes # (issue)
#82 
## Checklist

* [x] I followed the guidelines in our Contributing document
* [x] I added an explanation of my changes

## Additional notes (optional)

2023-03-30 21:52 UTC, chris-greening requested changes

2023-03-30 21:52 UTC, chris-greening commented on spyrograph/hypotrochoid/hypocycloid.py
> +    the curve.
Please remove the "for computing the length, area, and curvature of the curve, as well as" as Hypocycloid currently doesn't have this behavior

2023-03-31 03:23 UTC, jbxamora reviewed
Done!

2023-03-31 04:07 UTC, chris-greening approved these changes

2023-03-31 04:07 UTC, merged

2023-03-31 04:07 UTC, chris-greening commented
Fantastic work @jbxamora - thanks so much!