Improved the `Epicycloid` class docstring
chris-greening/spyrograph pull request #86
Opened 2023-03-30 21:16 UTC by jbxamora

## Description
Simple improvement of docstring to make it more technical and concise
Do not include any personal data.

Fixes # (issue)

## Checklist

* [x] I followed the guidelines in our Contributing document
* [x] I added an explanation of my changes

## Additional notes (optional)

2023-03-30 21:50 UTC, chris-greening requested changes

2023-03-30 21:50 UTC, chris-greening commented on spyrograph/epitrochoid/epicycloid.py
> +    the curve.
Can you please remove "for computing the length, area, and curvature of the curve, and"

spyrograph currently doesn't do this

2023-03-30 21:50 UTC, chris-greening commented on spyrograph/epitrochoid/epicycloid.py
> +    where the rolling circle has a radius that is one-third the radius of the fixed circle.
Please remove the second sentence as "one-third the radius of the fixed circle." is not relevant to this particular example

2023-03-30 21:51 UTC, chris-greening commented
Heyo @jbxamora !! Thanks so much for your contribution, I just flagged some slight tweaks 😄

2023-03-31 03:21 UTC, jbxamora reviewed
Got it! Here you go

2023-03-31 03:26 UTC, jbxamora reviewed
Pylint

2023-03-31 04:06 UTC, chris-greening approved these changes

2023-03-31 04:07 UTC, merged